server.port=4000





############ PostgreSQL Connection  ###########
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Sourav@25%
# Schema Configuration
#spring.jpa.properties.hibernate.default_schema=ecommerce

# Flyway Configuration
spring.flyway.enabled=true
spring.flyway.validate-on-migrate=false
spring.flyway.repair-on-migrate=true
spring.flyway.baseline-on-migrate=true




app.application-mode=DEV
#  //PROD

app.jwt.secret=fdsgfdsffffffffffffffffffffffffffffffffffffffffff
app.jwt.expiration-ms=50000
app.cors.allowed-origins=http://localhost:4000,http://127.0.0.1:4000


############ MAIL  ##############
notification.mail.host=${MAIL_HOST:smtp.zoho.in}
notification.mail.port=${MAIL_PORT:465}
notification.mail.username=${MAIL_USERNAME:souravdas23@zohomail.in}
notification.mail.password=${MAIL_PASSWORD}
notification.mail.protocol=${MAIL_PROTOCOL:smtp}
notification.mail.auth=${MAIL_AUTH:true}
notification.mail.isTlsEnable=${MAIL_IS_TLS_ENABLE:true}
notification.mail.isDebug=${MAIL_IS_DEBUG:true}

################# File Storage Credential #############
storage.cloudinary.url=${CLOUDINARY_URL:}
storage.cloudinary.cloud-name=${CLOUD_NAME:}
storage.cloudinary.api-key=${CLOUD_API_KEY:}
storage.cloudinary.api-secret=${CLOUD_API_SECRET:}

storage.imagekit.private-key=${IMAGEKIT_PRIVATE_KEY:=}

storage.imagekit.webhook-secret=${IMAGEKIT_PRIVATE_KEY}