server.port=4000





############ PostgreSQL Connection  ###########
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
spring.datasource.username=postgres
spring.datasource.password=Sourav@25%
# Schema Configuration
#spring.jpa.properties.hibernate.default_schema=ecommerce



app.application-mode=DEV
#  //PROD

app.jwt.secret=fdsgfdsffffffffffffffffffffffffffffffffffffffffff
app.jwt.expiration-ms=50000
app.cors.allowed-origins=http://localhost:4000,http://127.0.0.1:4000


############ MAIL  ##############
mail.host=${MAIL_HOST:smtp.zoho.in}
mail.port=${MAIL_PORT:465}
mail.username=${MAIL_USERNAME:souravdas23@zohomail.in}
mail.password=${MAIL_PASSWORD}
mail.protocol=${MAIL_PROTOCOL:smtp}
mail.auth=${MAIL_AUTH:true}
mail.isTlsEnable=${MAIL_IS_TLS_ENABLE:true}
mail.isDebug=${MAIL_IS_DEBUG:true}
